// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA_kuDrabVKiP6CyKopFhDutnAiv18qDM',
    appId: '1:866729725731:web:decd299e494b6c3942c696',
    messagingSenderId: '866729725731',
    projectId: 'messanger-66f89',
    authDomain: 'messanger-66f89.firebaseapp.com',
    storageBucket: 'messanger-66f89.appspot.com',
    measurementId: 'G-G1RJ01G4ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC49B8zsmGXREOpihgJU4-ZRaMPYJW0-N8',
    appId: '1:866729725731:android:d572353bcba3584042c696',
    messagingSenderId: '866729725731',
    projectId: 'messanger-66f89',
    storageBucket: 'messanger-66f89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Zq9Gel0r93Bh93r00Zlenwswz5hl_TM',
    appId: '1:866729725731:ios:adc059ac8967eef742c696',
    messagingSenderId: '866729725731',
    projectId: 'messanger-66f89',
    storageBucket: 'messanger-66f89.appspot.com',
    iosBundleId: 'com.example.messanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4Zq9Gel0r93Bh93r00Zlenwswz5hl_TM',
    appId: '1:866729725731:ios:c42234398889fe4e42c696',
    messagingSenderId: '866729725731',
    projectId: 'messanger-66f89',
    storageBucket: 'messanger-66f89.appspot.com',
    iosBundleId: 'com.example.messanger.RunnerTests',
  );
}
