// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj4XRPZWPib5B09tj1W40y6Gm2iTOzokk',
    appId: '1:992590573954:web:29b05f1b20545c0be25f9b',
    messagingSenderId: '992590573954',
    projectId: 'notification-ae472',
    authDomain: 'notification-ae472.firebaseapp.com',
    storageBucket: 'notification-ae472.appspot.com',
    measurementId: 'G-VR3SZJQX89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMWXD-cTCxx57exhlnJUjhBonT6KAIsmk',
    appId: '1:992590573954:android:12c7b2f6cd5fa4b6e25f9b',
    messagingSenderId: '992590573954',
    projectId: 'notification-ae472',
    storageBucket: 'notification-ae472.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz_68zqfAHzx4wlz7gLGiyJaMYOvQB9nY',
    appId: '1:992590573954:ios:64d2df77948408ece25f9b',
    messagingSenderId: '992590573954',
    projectId: 'notification-ae472',
    storageBucket: 'notification-ae472.appspot.com',
    iosBundleId: 'com.example.messanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz_68zqfAHzx4wlz7gLGiyJaMYOvQB9nY',
    appId: '1:992590573954:ios:4de4881eb4443189e25f9b',
    messagingSenderId: '992590573954',
    projectId: 'notification-ae472',
    storageBucket: 'notification-ae472.appspot.com',
    iosBundleId: 'com.example.messanger.RunnerTests',
  );
}
