// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ_ukzi_MXkHHiws5k57OAG8K2MpwIGDA',
    appId: '1:434548691820:web:846137eaa36807429f1949',
    messagingSenderId: '434548691820',
    projectId: 'mymessangerapp-423de',
    authDomain: 'mymessangerapp-423de.firebaseapp.com',
    storageBucket: 'mymessangerapp-423de.appspot.com',
    measurementId: 'G-W297Z5KFGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkX-_mxw9BazkJRfPQHh6md8y8vSBkUcQ',
    appId: '1:434548691820:android:0dd4004de08213609f1949',
    messagingSenderId: '434548691820',
    projectId: 'mymessangerapp-423de',
    storageBucket: 'mymessangerapp-423de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsCbbuRX_mCGyF6ZVkS58joWYtnhz72Tg',
    appId: '1:434548691820:ios:0d942a0f2c40b6909f1949',
    messagingSenderId: '434548691820',
    projectId: 'mymessangerapp-423de',
    storageBucket: 'mymessangerapp-423de.appspot.com',
    iosBundleId: 'com.example.messanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsCbbuRX_mCGyF6ZVkS58joWYtnhz72Tg',
    appId: '1:434548691820:ios:fa3bb7f173f2cc489f1949',
    messagingSenderId: '434548691820',
    projectId: 'mymessangerapp-423de',
    storageBucket: 'mymessangerapp-423de.appspot.com',
    iosBundleId: 'com.example.messanger.RunnerTests',
  );
}
